# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Daily Algorithms
on:
  schedule:
    - cron: 05 16 * * *
  workflow_dispatch:

jobs:
  create_issue:
    name: Create algorithms issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Today's date
        run: echo "TODAY=$(TZ=UTC-8 date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Read List
        id: readList
        run: |
          content=`ls $PWD`
          # the following lines are only required for multi line json
          # content="${content//'%'/'%25'}"
          # content="${content//$'\n'/'%0A'}"
          # content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo $content
          echo "::set-output name=list::$content"
      - run: |
          # echo "${{fromJson(steps.readList.outputs.list).easy}}"
          echo "${{steps.readList.outputs.list}}"
      - name: Create algorithms issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: ""
          labels: "Daily Algorithms"
          title: "${{ env.TODAY }}"
          body: ""
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
